# Generated by Django 6.0.4 on 2026-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], default='venda', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('pronto', 'pronto'), ('em construção', 'em construção'), ('lancamento', 'lancamento'), ('na planta', 'na planta')], default='joâo pessoa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(choices=[('João Pessoa', 'João Pessoa'), ('Mediaçoes', 'Mediações')], max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('casa', 'casa'), ('apartamento', 'apartamento'), ('terreno', 'terreno'), ('comercial', 'comercial'), ('cobertura', 'cobertura'), ('flat', 'flat'), ('condominio fechado', 'condominio fechado')], max_length=20),
        ),
    ]
