# Generated by Django 4.2.7 on 2026-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_finalidade_imovel_status_alter_imovel_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('locacao', 'Locação'), ('arrendar', 'Arrendar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('pronto', 'Pronto'), ('construcao', 'Em Construção'), ('lancamento', 'Lançamento'), ('na_planta', 'Na Planta')], max_length=20),
        ),
    ]
