# Generated by Django 6.0.4 on 2026-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_alter_imagem_imagem_alter_imovel_imagem_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='imagem_principal',
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_vaga',
            field=models.CharField(blank=True, choices=[('Fixa', 'Fixa'), ('Rotativa', 'Rotativa')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiros',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(choices=[('João Pessoa', 'João Pessoa'), ('Cabedelo', 'Cabedelo'), ('Conde', 'Conde')], max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
